github:
  features:
    # Enable issue management
    issues: true

notifications:
  commits:      commits@petri.apache.org
  issues:       discuss@petri.apache.org
  pullrequests: discuss@petri.apache.org

pelican:
  notify:         commits@petri.apache.org
  target:         asf-site
  theme:          theme/apache
  whoami:         master

staging:
  whoami: dfoulks/gha-site
  profile: gha-site
  autostage: preview/*

