name: Build a Pelican Website
on:
  push:
    # This prevents the workflow from running automatically on a new branch
    # When creating a new site branch, please ensure that the push and checkout branches agree
    # and that the action/pelican destination value is updated accordingly
    branches: [ 'preview/**' ]
  workflow_dispatch:


jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: apache/infrastructure-actions/pelican@main
        with:
          destination: ${{ github.event.ref }}-site
