name: Build a Pelican Website
on:
  push:
    branches: 
      - 'preview/**'
  pull_request:
    branches: 
      - 'preview/**'
  workflow_dispatch:


jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.head_ref || github.ref }}
      - name: Determine branch name
        id: determine_branch
        run: |
          # Get the current branch name
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - name: Branch
        id: determine_output_branch
        run: |
          echo "Branch: ${{ env.BRANCH_NAME }}"
          if [ "${{ env.BRANCH_NAME }}" == "${{ github.event.repository.default_branch }}" ]; then
            echo "OUTPUT_BRANCH=asf-site" >> $GITHUB_ENV
          else
            echo "OUTPUT_BRANCH=${{ env.BRANCH_NAME }}-staging" >> $GITHUB_ENV
          fi
      - name: Pelican  Build
        uses: apache/infrastructure-actions/pelican@main
        with:
          destination: ${{ env.OUTPUT_BRANCH }}
