name: Build a Pelican Website
on:
 push:
 branches: [ 'master' ]
 workflow_dispatch:
jobs:
 build-pelican:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v4
 with:
 ref: 'master'
 - uses: apache/infrastructure-actions/pelican@main
 with:
 destination: 'asf-site'
 gfm: 'true'
