name: Build a Pelican Website
on:
  push:
    branches: 
      - 'preview/**'
  pull_request:
    branches: 
      - 'preview/**'
  workflow_dispatch:


jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.head_ref || github.ref }}
      - name: Determine branch name
        id: get_branch
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "push" ]; then
            echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.branch }}" != "" ]; then
              echo "BRANCH_NAME=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
            else
              echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
            fi
          fi
      - name: Branch
        run: |
          echo "Branch: ${{ env.BRANCH_NAME }}"
          if [ "${{ env.BRANCH_NAME }}" == "${{ github.event.repository.default_branch }}" ]; then
            echo "OUTPUT_BRANCH=asf-site" >> $GITHUB_ENV
          else
            echo "OUTPUT_BRANCH=${{ env.BRANCH_NAME }}-staging" >> $GITHUB_ENV
          fi
      - name: Pelican  Build
        uses: apache/infrastructure-actions/pelican@main
        with:
          destination: ${{ env.OUTPUT_BRANCH }}
